### create book
POST  http://localhost:3001/books
Content-Type: application/json

{
  "title": "Dune",
  "author": "Frank Herbert",
  "genre": "Science Fiction",
  "publishedDate": "1965-08-01",
  "status": "read",
  "rating": 5,
  "description": "Epic world-building and politics"
}


### get books
GET http://localhost:3001/books
Content-Type: application/json


### get book by id
GET http://localhost:3001/books/6834ada6c8c0d4f7a925515
Content-Type: application/json


### update book by id put
PUT http://localhost:3001/books/6834b6b40cfb415f406b5e7f
Content-Type: application/json

{
  "title": "Atomic Habits 3",
  "author": "James rocks",
  "genre": "Self-help",
  "publishedDate": "2018-10-16",
  "status": "read",
  "rating": 5,
  "notes": "Very insightful!"
}

### delete book by id delete
DELETE http://localhost:3001/books/6834ae9b20804c39b48ccb70
Content-Type: application/json

/////////////////////////////////////////////////////////////////
### create users
POST  http://localhost:3001/users
Content-Type: application/json

{
   "name": "Diego",
  "lastName": "Fernandez",
  "email": "diego.fernandez@sample.org"
}

### get users
GET http://localhost:3001/users
Content-Type: application/json


### get users by id
GET http://localhost:3001/users/6834d874e56787a7f2d5ead8
Content-Type: application/json


### update users by id put
PUT http://localhost:3001/users/6834d874e56787a7f2d5ead8
Content-Type: application/json

{
    "name": "Monica",
    "lastName": "Vasquez",
    "email": "monica@test.com"
}

### delete book by id delete
DELETE http://localhost:3001/users/6834d874e56787a7f2d5ead8
Content-Type: application/json
